### ISSUE TITLE
Submit to upstream packer

### ISSUE THREAD

**Issue by imduffy15** [vtolstov/packer-post-processor-shell#2]
Hey,

Any reason for not submitting this back into packer upstream? :)

**Comment by vtolstov** [comment]
I'm already have issue in packer, but nobody looks for merge.

**Comment by imduffy15** [comment]
Hey @vtolstov 

Thanks for getting back to me. Took a quick look at the packer PRs, not seeing any one addressing this: https://github.com/mitchellh/packer/pulls/vtolstov

I've downloaded and tested it manually on a few builds. Seems to of worked well, I noticed a slight bug. The value for the $PACKER_BUILDER_TYPE variable had extra single quotes and escape slashes. 

Along with this, if the {{.Provider}} variable was supplied in the environmental variable map it wouldn't pass successfully... Pretty sure this is an issue with template rendering rather than your plugin though.

**Comment by vtolstov** [comment]
I'm not create pr for it, i'm only create issue and say that somebody review =)/ <ay be this is time to create pr

**Comment by imduffy15** [comment]
Okay no problem :)

I ended up re-writing bits of it last night: https://github.com/imduffy15/packer-post-processor-shell

Followed a mixed up flow of the shell and local-shell provisioner. I wanted the output of the scripts to show up on the packer output. Also appears to of fixed the escaping issue.

I want to write some tests around it and will send a PR your way. We can approach upstream after that. 

Thanks again for creating this :)

**Comment by vtolstov** [comment]
Thanks! Also you need to implement DownloadDir as i'm create pr to add this to communicator interface (works for ssh only now)

**Comment by vtolstov** [comment]
Also as i see you forget to pass artifact name for script. I'm prefer iterate over artifact.Files() and pass artifact name to first arg.

**Comment by imduffy15** [comment]
I was trying to work out why you did that! I'll look into it again later...
I was assuming environmental variables would survive.

**Comment by vtolstov** [comment]
I think that env variables for env variables =) but each script need to be run on artifact, so artifact path is the argument to script.

**Comment by imduffy15** [comment]
A builder may output multiple artifact though. For example, the vmware builder outputs:

```
        ├── centos6-java-2.0.0.nvram
        ├── centos6-java-2.0.0.vmsd
        ├── centos6-java-2.0.0.vmx
        ├── centos6-java-2.0.0.vmxf
        ├── disk-cl1-s001.vmdk
        ├── disk-cl1-s002.vmdk
        └── disk-cl1.vmdk
```

I'm not seeing the use case for wanting to pass each one of them to an external script with the requirement to do filtering.....

**Comment by vtolstov** [comment]
@imduffy15 i don't see problems to filter this in script, but if you not pass all files - you stuck at artific post processor , because it have ability to override artifacts.

**Comment by beddari** [comment]
I can see where you are coming from @vtolstov but I think it is best (least suprising) to actually require artifice for overriding the artifacts list. Just my 2c.

**Comment by imduffy15** [comment]
Good call @beddari I can agree to that.

Our use case for this is to push a vagrant box to external storage. Support for artifice or vagrant makes sense.
